### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Fixed typo, in Heading, Repositaries => Repositories

### CODE REVIEW

**Review by NS007-dev — APPROVED** [review]
@Programmer005 thank you! I didn't notice the typo, LGTM.

**Comment by AvidCoder101** [comment]
@all-contributors please add @Programmer005 for content

**Comment by CodingSpecies** [comment]
@all-contributors please add @Programmer005  for content

**Comment by AvidCoder101** [comment]
@Programmer005 I have invited you to the organization.

**Comment by AvidCoder101** [comment]
@all-contributors please add @Programmer005 for content

**Comment by AvidCoder101** [comment]
@all-contributors please add @Programmer005 for content

**Pull request merged**
