### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NS007-dev**

### CODE REVIEW

**Comment by NS007-dev** [comment]
@all-contributors please add @AvidCoder101  for project management

**Comment by NS007-dev** [comment]
@all-contributors please add @JayantGoel001 for content and documentation

**Comment by NS007-dev** [comment]
@all-contributors please add @CodingSpecies  for content

**Comment by AvidCoder101** [comment]
@all-contributors please add @Bikram-ghuku for content

**Comment by AvidCoder101** [comment]
@all-contributors please add @akshatmittal61 for content

**Comment by AvidCoder101** [comment]
@all-contributors please add @akshatmittal61 for content

**Pull request merged**
